name: Deploy to Aliyun OSS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ossutil
        run: |
          wget https://gosspublic.alicdn.com/ossutil/1.7.16/ossutil64
          chmod +x ossutil64
          mv ossutil64 /usr/local/bin/ossutil

      - name: Configure ossutil
        run: |
          ossutil config -e ${{ secrets.OSS_ENDPOINT }} -i ${{ secrets.OSS_ACCESS_KEY_ID }} -k ${{ secrets.OSS_ACCESS_KEY_SECRET }}

      - name: Sync to OSS (with delete)
        run: |
          ossutil sync ./ oss://${{ secrets.OSS_BUCKET }}/ --delete --force 